---
sqlite3: &sqlite3
  adapter: sqlite3
  timeout: 1000

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i + 2 } %>

development:
  primary:
    <<: *sqlite3
    database: db/development/primary.sqlite3
  cache:
    <<: *sqlite3
    database: db/development/cache.sqlite3
    migrations_paths: db/development/cache_migrate
  queue:
    <<: *sqlite3
    database: db/development/queue.sqlite3
    migrations_paths: db/development/queue_migrate
  rack_attack:
    <<: *sqlite3
    database: db/development/rack_attack.sqlite3
    migrations_paths: db/development/rack_attack_migrate

test:
  primary:
    <<: *sqlite3
    database: db/test/primary.sqlite3
  cache:
    <<: *sqlite3
    database: db/test/cache.sqlite3
    migrations_paths: db/test/cache_migrate
  queue:
    <<: *sqlite3
    database: db/test/queue.sqlite3
    migrations_paths: db/test/queue_migrate
  rack_attack:
    <<: *sqlite3
    database: db/test/rack_attack.sqlite3
    migrations_paths: db/test/rack_attack_migrate

production:
  primary:
    <<: *default
    database: lobsters_primary
  cache:
    <<: *default
    database: lobsters_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: lobsters_queue
    migrations_paths: db/queue_migrate
  rack_attack:
    <<: *default
    database: lobsters_rack_attack
    migrations_paths: db/rack_attack_migrate
